name: Grivie Scrapers

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    name: "Menjalankan Scraping dan Menyimpan Data"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Mengambil kode repositori
        uses: actions/checkout@v4

      - name: Menyiapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Menginstal Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb -y

      - name: Menginstal dependensi Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Menjalankan skrip scraper
        run: python scraper.py

      - name: Commit dan push jika ada perubahan
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update: Sinkronisasi data produk setiap jam"
          file_pattern: product.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>

      # --- LANGKAH NOTIFIKASI WHATSAPP (LANGSUNG) ---
      - name: Kirim notifikasi WhatsApp jika ada perubahan
        if: steps.commit.outputs.changes_detected == 'true'
        run: |
          curl -X POST \
          -H "Authorization: xZK6mMwiSqnJgaqtBqEHF2REyHeeCwqYnVQLgNvJ3hbe" \
          -H "Content-Type: application/json" \
          -d '{
            "target": "6285736058049",
            "message": "✅ Scraping data produk berhasil diperbarui."
          }' \
          https://api.fonnte.com/send
