name: Scrape Jagel Data (Efisien)

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    name: "Menjalankan Scraping dan Menyimpan Data"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Mengambil kode repositori
        uses: actions/checkout@v4

      - name: Menyiapkan cache untuk dependensi Python
        # Langkah ini akan menyimpan library dari requirements.txt
        # agar tidak perlu diunduh ulang setiap kali dijalankan.
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Menyiapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalasi Chromium (jika belum ada)
        # Logika ini memeriksa apakah 'chromium-browser' sudah bisa ditemukan.
        # Jika belum, maka akan menjalankan instalasi.
        run: |
          if ! command -v chromium-browser &> /dev/null
          then
            echo "Chromium tidak ditemukan. Memulai instalasi..."
            sudo apt-get update
            sudo apt-get install -y chromium-browser
          else
            echo "Chromium sudah terpasang."
          fi

      - name: Menginstal dependensi Python
        # 'pip' akan menggunakan cache dari langkah sebelumnya jika ada.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Menjalankan skrip scraper
        run: python scraper.py

      - name: Commit dan push jika ada perubahan
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update: Sinkronisasi data produk setiap jam"
          file_pattern: product.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>

      - name: Kirim notifikasi WhatsApp jika ada perubahan
        if: steps.commit.outputs.changes_detected == 'true'
        run: |
          # Ganti dengan token dan nomor telepon Anda jika menggunakan metode langsung
          # atau gunakan secrets jika menggunakan metode aman.
          curl -X POST \
          -H "Authorization: ${{ secrets.FONNTE_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "target": "${{ secrets.WHATSAPP_PHONE }}",
            "message": "✅ Scraping data produk berhasil diperbarui."
          }' \
          https://api.fonnte.com/send
