name: Scrape Jagel Data

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape-and-commit:
    name: "Menjalankan Scraping dan Menyimpan Data"
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Mengambil kode repositori
        uses: actions/checkout@v4

      - name: Menyiapkan cache untuk dependensi Python
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Menyiapkan Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalasi Chromium Browser
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Menginstal dependensi Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Menjalankan skrip scraper
        run: python scraper.py

      - name: Commit dan push jika ada perubahan
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update: Sinkronisasi data produk setiap jam"
          file_pattern: product.json
          commit_user_name: GitHub Actions Bot
          commit_user_email: actions@github.com
          commit_author: GitHub Actions Bot <actions@github.com>
